version: 0.2
phases:
  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore DemoAPI/DemoAPI.csproj
  build:
    commands:
      - echo Build started on `date`
      - dotnet publish -c release -o ./build_output DemoAPI/DemoAPI.csproj
artifacts:
  files:
    - build_output/**/*